language: cpp

os: linux

git:
  depth: 1

addons:
  apt:
    packages:
    - libprotobuf-dev
    - protobuf-compiler

stage_test: &test
  stage: "Build test"
  script: cmake . && make && make install

jobs:
  include:
    - <<: *test
      os: linux
      dist: focal
    - <<: *test
      os: linux
      dist: bionic
    - <<: *test
      os: linux
      dist: xenial
